# Reduction, Beauty and Peril {#reduction}

Initially, we tried to generate 100 large instances of 3SAT and try to reduce those to Decision 0-1 Knapsack and use either <span style="font-variant:small-caps;">MaxValDP</span> or <span style="font-variant:small-caps;">MinCostDP</span> to solve them. Nevertheless, we face problems with memory. This ceases any further attempts we made. We found 2 optimization that potentially allows us to have instances of 3SAT with just 1 clause working, but we deem this as minimal and not actually put in effort to execute that. We will give our excuse for this _sloth_ later in this section.

There is definitely something of beauty about the reduction from 3SAT to Decision 0-1 Knapsack. We will not go through the full proof but just key points in the reductions; (again) for the elegant, complete explanation, we recommend reading _What Is A Computer and What Can It Do?_. 

In the reduction from 3SAT to 1in3SAT, a clause like $(x_1 \lor x_2 \lor x_3)$ in the 3SAT problem instance will correspond to 3 clauses in 1in3SAT problem instance, i.e. 
$$(\bar{x}_1 \lor a \lor b)\land (b \lor x_2 \lor c)\land (c \lor d \lor \bar{x}_3)$$
As we can see, we must triple the number of clauses and add 4 new variable. The reduction from 1in3SAT to SubsetSum, we create a pair of number $v_i$ and $v'_i$ for each variable $x_i$--this pair of numbers are made up of 1's and 0's to represent truth assignment of the corresponding variable as well as its impact to each clause--in the 1in3SAT instance; the target sum is of the length of each number in the set but made up of all 1's. The number of digits used for each new number equals to the sum of the number of clauses in the number of variables in the 1in3SAT problem instance. To reduce from SubsetSum to Decision 0-1 Knapsack, for each number in the set, we create an item with cost and value equal to that number. Then both the target and the budget are set to the target sum. As such, when using Maximum 0-1 Knapsack solvers, we are forced to choose the optimal value that equals (no more, no less) than the budget; and because we require this exactness, we must use dynamic programming algorithms to find the optimal value instead of using any approximation-based algorithms.

This chain of reductions is straight forward to code, but there is a problem. Let say we start with the minimal instance of 3SAT, with just 1 clause and 2-3 variables, then the budget and the maximum value of an item will be at of 9-10 digits (3 clauses and 6-7 variables in the 1in3SAT problem instance). We tested the 3SAT instance $(x_{0} \lor \bar{x}_{0} \lor \bar{x}_{1})$, which, after reduction, results in the following Knapsack problem instance:
```
Budget: 111111111
Target: 111111111
Max Value: 100000100
Item:
  1. Value: 100000010, Cost: 100000010
  2. Value: 100000100, Cost: 100000100
  3. Value: 10000000, Cost: 10000000
  4. Value: 10000001, Cost: 10000001
  5. Value: 1000100, Cost: 1000100
  6. Value: 1000000, Cost: 1000000
  7. Value: 100110, Cost: 100110
  8. Value: 100000, Cost: 100000
  9. Value: 10011, Cost: 10011
  10. Value: 10000, Cost: 10000
  11. Value: 1001, Cost: 1001
  12. Value: 1000, Cost: 1000
```

For this kind of situation, when we try to solve this Decision 0-1 Knapsack problem using either dynamic programming approach, Java will respond with the exception **java.lang.OutOfMemoryError: Java heap space.** The problem exacerbates when we use more than 2 clauses. For example, we tested out $$(x_{0} \lor \bar{x}_{1} \lor \bar{x}_{2}) \land (x_{0} \lor x_{2} \lor x_{3})$$ and go back the exception **java.lang.NumberFormatException: For input string: "111111111111111111"** as we try to construct the target sum for our SubsetSum problem. The reason is that we use Integer type for numbers in the SubsetSum problem instance, which only accommodates to the maximum value of $2^{32} \approx 4.3e9$.

As such, we thought of a few optimization in hope that it can improve the situation. For the number format problem, we can use type Long instead of Integer; even better, we can leave the number as String and use BigInteger class in Java to perform calculation with big numbers. The bigger problem, though, lies in the implementations of the algorithms used to solve Decision 0-1 Knapsack. Both dynamic programming approaches requires the construction of tables which base on either the budget (for <span style="font-variant:small-caps;">MaxValDP</span>) or the maximum value of an item (for <span style="font-variant:small-caps;">MinCostDP</span>). These numbers as shown above are too big and thus, such table drains memory really fast. 

We observe that although these are really big table, they are really sparse. As such, we can try to use linked list to represent such sparse table. If we use a single linked-list, if we increases the number of clauses, time taken to iterates through all the nodes will be absurd. If we use 2 linked-list, each of which represent header cells of the table' columns and rows, then we will end up with a linked-list of about a billion nodes or more, which also causes Java heap space to run out of memory.

Another observation we have is that since all numbers coming out of the SubsetSum problem instance consist of only 0 and 1, we can think of these number as binary and feed those number to Maximum 0-1 Knapsack solvers. Nevertheless, for this approach, we have tried to use 2 SAT clauses and yet again a table with $2^{20}$ column is still too big for Java to handle. We also think of an optimization where while reducing from 1in3SAT to SubsetSum, we can actually disregard the variable part in each number and only care about the clause part for each pair $v_i$ and $v'_i$. The reason why we include the literal part is to make sure that we cannot choose both $v_i$ and $v'_i$ for the same value of $i$. As such, we can omit this part of the number and modify our algorithm slightly to do this check. One potential way is to keep track of which item is being taken, i.e. $v_i$ is chosen, and thus skip $v'_i$ while building further rows. 

Even with this optimization, we only increase the number of clauses possible for the 3SAT problem instance to have to 2. And 2 clauses will correspond to a knapsack problem instance with 14 items. The result obtained from these considerably _small_ Knapsack problem instance are not really reliable due to randomness in the problem generation phase. Also, it is expected that the running time of <span style="font-variant:small-caps;">MinCostDP</span> will be punished by the term $n^2$ whereas by the way we construct the numbers for the SubsetSum problem instance, the ratio $\frac{\text{budget}}{\text{maxValue}}$ will be approximately 1; and so we will find <span style="font-variant:small-caps;">MinCostDP</span> takes absurdly longer to run as compared to <span style="font-variant:small-caps;">MaxValDP</span>.

Through this section, we have presented the _peril_ part of this experiment. We surely learned a lot out of it, i.e. that sometimes a theoretically brilliant approach might end up with no practically sound implementation. Perhaps, this could also due to our incompetence but for now, we decide to just move on with the other experiment, exploring the 4 flavors of Maximum 0-1 Knapsack solvers. 

