# Conclusion {#conclusion}
We can come up with the conclusion that <span style="font-variant:small-caps;">MaxValDP</span>, the vanilla flavor, shows why it is generally favored. It guarantees the optimal value (with 100% accuracy) and relatively acceptable running time. The versatile <span style="font-variant:small-caps;">FPTAS</span> actually does worse in both aspect, accuracy and running time; but to do justice to it, it shines for its versatility; as compared to other approximation method which targets a specific range of error, e.g. <span style="font-variant:small-caps;">Greedy</span>, it will not perform as good, otherwise, we will deem <span style="font-variant:small-caps;">Greedy</span> as useless and get rid of it. <span style="font-variant:small-caps;">Greedy</span>, though, runs amazingly fast and yields acceptable accuracy. The last flavor, <span style="font-variant:small-caps;">MinCostDP</span> is like chocolate. Hardly can anyone argue whether chocolate or vanilla is ultimately the better flavor. Perhaps, even on situational basis: it is actually pretty hard to come up with an example to show that a type of pastries must come with chocolate instead of vanilla ... apparently brownies can also come with vanilla. We guess the moral of the story is not that you can use either dynamic programming approach to solve any Maximum 0-1 Knapsack problem, but some go better with <span style="font-variant:small-caps;">MaxValDP</span> and others go better with <span style="font-variant:small-caps;">MinCostDP</span>, such as those problems with really high maximum value.